services:

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es02
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security
      - xpack.security.transport.ssl.enabled=false  # Disable transport SSL
    deploy:
      resources:
        limits:
          memory: 1GB
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.3
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 5001:5001
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic

  kib02:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kib02
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: "bridge"